# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: remyniscent
email: ms.vohuyenmy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  remyniscent sample
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mi.cc" # the base hostname & protocol for your site

# setup link by category
permalink: /:categories/:year/:month/:day/:title
# Build settings
markdown: kramdown

port: 4444
